# This is a basic workflow to help you get started with Actions

name: RUN SHELL SCRIPT
on:
  push:
    branches:
    - dev
jobs:
  run_tests:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Run script file
      run: |
         chmod +x test.sh
         sh test.sh
      shell: bash
